const express = require('express');
const cors = require('cors');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());
app.use((req, res, next) => {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.header("Access-Control-Allow-Headers", "Origin, Content-Type, Accept");
  next();
});
app.use(express.static(__dirname));

let reviews = [
  "The confidence I gained after getting braces here is priceless. Clean clinic, courteous staff, and timely follow-ups. Best orthodontist in Amritsar.",
  "I've tried multiple clinics before, but this is the only one I trust now. Excellent in every way. Best dental clinic in Amritsar — no exaggeration.",
  "As an NRI visiting from New Zealand, I was hesitant. But their transparent treatment plans and outstanding execution proved why they're the best dental clinic in Amritsar.",
  "I was very concerned about the look of my teeth. After cosmetic contouring and whitening here, I can't stop smiling. Best dentist in Amritsar for aesthetics.",
  "For kids and adults alike, this clinic provides equal attention. Got fluoride treatment for my son and it was very smooth. Best dental clinic in Amritsar for families.",
  "If you want painless dentistry, come here. I didn't even feel the injection during my root canal. Dr. Keshvi is the best dentist in Amritsar for sensitive treatments.",
  "Braces were a breeze here. Every month's adjustment was on time and well-managed. Dr. Ankur is undoubtedly the best orthodontist in Amritsar.",
  "Digital X-rays, intraoral cameras, and detailed consultation — it felt like a premium experience. Best dental clinic in Amritsar, technologically speaking.",
  "I wanted Hollywood-style veneers, and the results were spot-on. Great finish, natural look. Best cosmetic dentist in Amritsar.",
  "Emergency toothache during my Punjab visit led me here. Immediate relief and fantastic care. I now refer to them as the best dentist in Amritsar.",
  "They handled my wisdom tooth surgery with such precision that I felt no pain at all. Best dental clinic in Amritsar for oral surgery.",
  "I came in for teeth cleaning and ended up getting detailed counseling on dental hygiene. The doctor's approach was sincere. Best dentist in Amritsar for preventive care.",
  "Had gum reshaping done, and the results are aesthetically pleasing. The doctor has an eye for detail. Best dental clinic in Amritsar for laser treatments.",
  "The implants done here are indistinguishable from my real teeth. Dr. Keshvi is hands down the best dental implant specialist in Amritsar.",
  "The best part was that they respected my time. No unnecessary wait, no delays. Just great dental care. Best dental clinic in Amritsar, period.",
  "I am recommending this place to everyone I know. Their dental work speaks for itself. Best dentist in Amritsar for honest service.",
  "The root canal was so smooth, I actually dozed off in the chair! That's how painless and professional they are. Best dental clinic in Amritsar for endodontic care.",
  "My braces were taken off today, and my smile is unbelievable. The perfect alignment shows why Dr. Ankur is the best orthodontist in Amritsar.",
  "They offer complete transparency in cost and treatment plan. I never felt misled. Best dental clinic in Amritsar for ethical dentistry.",
  "I wanted a smile that looked good but still natural. They delivered beyond expectations. Best cosmetic dentist in Amritsar by far.",
  "As a Canadian citizen, I expect high standards in healthcare. This clinic met every expectation. Best dental clinic in Amritsar for international patients.",
  "I had a broken front tooth, and it was replaced with a zirconia crown. No one can tell the difference. Best dental implant clinic in Amritsar.",
  "Staff is well-trained and responsive. I had an emergency swelling, and they handled it professionally. Best dentist in Amritsar for prompt care.",
  "I got braces late in life, but never felt out of place here. Great support from the team. Best orthodontist in Amritsar for adult braces.",
  "Every treatment is documented, photos are shared, and progress is explained. This level of clarity is why it's the best dental clinic in Amritsar.",
  "My 7-year-old had his first dental visit here. It was smooth and fun. Best dental clinic in Amritsar for pediatric care.",
  "Had minor surgery for a cyst and everything was handled meticulously. Dr. Keshvi is the best dentist in Amritsar for surgical procedures.",
  "I've had gum problems for years, and after just three visits, my gums are pink and healthy again. Best dental clinic in Amritsar for gum disease treatment.",
  "This is more than a clinic — it's a place where your dental health is genuinely prioritized. I proudly call it the best dental clinic in Amritsar.",
  "Amazing experience! The best dental implant clinic in Amritsar with trained staff and international-level hygiene standards.",
  "Their smile design consultation was thorough and artistic. I now have the smile I always dreamed of. Best dentist in Amritsar for cosmetic work.",
  "My wife and I got teeth whitening done together and it was such a pleasant experience. This is the best dental clinic in Amritsar for couples and families.",
  "Dr. Keshvi is meticulous with her work. My full mouth implants feel so natural now. Best dental implant in Amritsar for sure.",
  "Highly recommended for anyone seeking precision and pain-free dental treatments. This is truly the best dentist in Amritsar.",
  "Quick service, great results, and reasonable pricing — definitely the best dental clinic in Amritsar for all types of dental issues.",
  "I was treated for gum recession, and their laser treatment worked wonders. Best dental clinic in Amritsar for periodontal issues.",
  "Their orthodontic work is subtle and efficient. My smile improved drastically without discomfort. Best orthodontist in Amritsar, without a doubt.",
  "You'll find transparency, hygiene, and world-class care here. Best dental clinic in Amritsar by far!",
  "Got braces at 40 and still had a wonderful journey. Dr. Ankur is a gem and the best orthodontist in Amritsar for adults.",
  "They treat elderly patients with patience and empathy. My father felt extremely comfortable. Best dentist in Amritsar for seniors.",
  "Can't believe how well my implants turned out. Dr. Keshvi is amazing — best dental implant expert in Amritsar!",
  "Dental cleaning, polishing, and oral hygiene tips all done under one roof. Best dental clinic in Amritsar for preventive care.",
  "I underwent a full smile makeover here, and I can't believe the results. The clinic exceeded my expectations in both aesthetics and comfort. Absolutely the best dental clinic in Amritsar for cosmetic dentistry.",
  "From consultation to treatment, everything was seamless. I had multiple fillings, and each was color-matched so well. This place deserves to be called the best dentist in Amritsar.",
  "I visited from the UK to get full mouth dental implants done. Dr. Keshvi made the process so comfortable and stress-free. No doubt, this is the best dental implant clinic in Amritsar.",
  "Dr. Ankur fixed my misaligned teeth with Invisalign, and now I have a perfectly aligned smile. Truly the best orthodontist in Amritsar with a patient-centered approach.",
  "After months of hesitation, I finally went ahead with veneers, and I'm in love with my smile now. Best dentist in Amritsar for cosmetic treatments, hands down!",
  "I had badly stained teeth due to smoking. Their teeth whitening procedure restored my confidence. Without a doubt, the best dental clinic in Amritsar.",
  "I came here for a dental emergency while visiting Amritsar from Canada. The staff acted promptly, and the treatment was flawless. Best dental care I've received.",
  "My teenage son had his braces done here, and the results are spectacular. Dr. Ankur is truly the best orthodontist in Amritsar for young patients.",
  "The hygiene and equipment are world-class. I got zirconia crowns and they look just like natural teeth. This is the best dental implant service in Amritsar.",
  "After years of dental anxiety, I finally found a place where I feel at ease. The doctors and staff are kind, professional, and gentle. Best dentist in Amritsar for anxious patients."
  "My daughter had two cavities, and the way the pediatric dentist handled it was amazing. This is definitely the best dental clinic in Amritsar for children.", "I was looking for a dentist who could fix my bite and speech issue. Dr. Keshvi diagnosed it instantly and resolved it with prosthetics. Best dentist in Amritsar for prosthodontics.", "Highly recommend for anyone seeking full mouth rehab. My treatment included implants, capping, and veneers — all done under one roof at the best dental clinic in Amritsar.", "The Damon braces I got from here were almost invisible and gave me the desired results in less than 12 months. Best orthodontist in Amritsar for modern braces.", "If you're seeking international-level dental care in Punjab, this clinic is it. The implants I got feel just like my original teeth. Best dental implant clinic in Amritsar, no question.", "Dr. Ankur made my daughter so comfortable with her first braces fitting. His calm approach makes him the best orthodontist in Amritsar.", "I visited from Australia and needed a complete dental checkup. From X-rays to polishing, everything was done with utmost professionalism. Best dental clinic in Amritsar for NRIs.", "I used to feel embarrassed about my teeth, but after visiting this clinic for smile designing, I feel like a new person. Truly the best dentist in Amritsar for transformations.", "Got zirconia caps on six teeth and they feel absolutely natural. The work is precise, and the staff is extremely warm. Best dental implant treatment in Amritsar.", "I had multiple root canals done and didn't feel any pain. Clean environment, updated equipment — definitely the best dental clinic in Amritsar for endodontics.", "Best dental clinic in Amritsar without a doubt. They explained every procedure, showed 3D scans, and made me feel safe throughout my treatment.", "Dr. Keshvi handled my case personally. I got full-mouth implants and every step was meticulously planned. Best dental implant expert in Amritsar.", "Very efficient appointment system. I've never had to wait. Their punctuality and professionalism make them the best dentist in Amritsar.", "The orthodontic treatment plan was so clear and well-executed. I was informed about every stage. Dr. Ankur is the best orthodontist in Amritsar for sure.", "Gum bleeding and sensitivity were bothering me for years. One sitting here changed everything. Best dental clinic in Amritsar for gum treatment.", "I highly recommend this place for seniors. My mother got dentures and the team ensured perfect fit and comfort. Best dental clinic in Amritsar for elderly care.", "Their sterilization protocols gave me confidence post-COVID. No compromise on hygiene. That's why they're called the best dentist in Amritsar.", "I had a fractured tooth and was worried about replacement. They suggested an implant and it's been great. Best dental implant in Amritsar!", "Had my smile corrected with composite bonding and couldn't believe how natural it looked. The treatment was quick, affordable, and gave me a brand-new smile.", "The best part about this clinic is how organized they are. I never had to wait long, and each appointment was conducted right on time. It shows they value your time as much as their own.", "Being from Australia, I was unsure about dental standards in India. But this clinic met international hygiene standards and delivered amazing results. I now trust them with my entire family's dental needs.", "I had an old crown replaced with a zirconia one, and I must say it feels and looks like a real tooth. The precision and aesthetic quality are unmatched. Truly the best dentist in Amritsar.", "Their staff is warm, welcoming, and fluent in English, which made communication easy. This really matters for NRIs like us visiting from abroad. Exceptional service from start to finish.", "After getting my teeth aligned through Damon braces, I now smile without hesitation. The entire orthodontic process was comfortable, and the results exceeded my expectations.", "I had a phobia of dentists due to a past experience, but the team here changed that completely. They're gentle, understanding, and always make sure I'm comfortable before starting anything.", "Had a customized smile designing consultation where they showed me a digital preview of my future smile. The final outcome matched exactly. Incredible technology and execution!", "Every little detail is taken care of—from sterilized tools to soft-spoken communication. It's a great experience every time. I won't trust any other dental clinic in Amritsar.", "The doctors explained every step during my dental implant procedure and never rushed through anything. I felt informed and safe, and now I can chew better than ever before.", "Brought my young son here for a checkup, and they were incredibly patient with him. The pediatric section is colorful and fun, making it easier for kids to adjust.", "After years of struggling with gum recession, I finally got relief with their periodontal treatment. The results are visible, and my gums no longer bleed. Highly recommended!", "I flew from the UK to visit this clinic and I must say, the experience exceeded every expectation. Dr. Keshvi was thorough, professional, and incredibly skilled at smile designing. I left India with a brand new smile and a boost in my confidence.", "This clinic has become my go-to for all dental concerns. From consultation to follow-up, every step was handled with care. The root canal I had was absolutely painless and completed in just one sitting—truly the best dental clinic in Amritsar.", "My father received full mouth rehabilitation here and the transformation has been phenomenal. He can eat comfortably, and his speech has improved as well. The attention to detail and compassion shown by Dr. Ankur made all the difference.", "The best part of this clinic is that you're not just treated as a patient, but as a person. They take time to understand your concerns and explain the procedures in detail. I came for a dental filling and ended up recommending them to my entire extended family.", "As someone who's always been anxious about dental visits, I felt completely at ease here. The team was patient, kind, and took their time during the treatment. Truly the most comfortable dental care experience I've ever had.", "I underwent smile designing treatment at this clinic and the results were beyond what I imagined. I can't stop smiling now! The precision and artistry they apply to dental work is commendable.", "This dental clinic combines international-grade hygiene with compassionate care. Being an NRI, I was worried about dental care standards in India, but this place rivals the clinics I've seen abroad.", "I needed zirconia crowns and came here based on reviews. Not only did they fit perfectly, but they also look better than my natural teeth. The clinic is clean, well-equipped, and staff is highly trained.", "My teenage son got his braces here and the entire process was seamless. The orthodontist team is knowledgeable, friendly, and highly skilled. Highly recommended for families looking for a reliable dental clinic.", "Got my full mouth implants done here after consulting multiple clinics. The difference in professionalism and care was obvious from day one. Thank you for giving me my smile and life back.", "From the moment you walk in, you can feel the positive and professional environment. They use modern techniques and genuinely care about patient comfort. Best dental clinic in Amritsar by far.", "Dr. Ankur's expertise and calm nature made my dental implant process stress-free. I had multiple missing teeth and now I can smile and chew with confidence again. Truly grateful.", "I'm from Australia and I travel to Amritsar regularly just for dental care from this clinic. Their hospitality, technology, and patient follow-up is unmatched.", "This clinic uses high-end tech like 3D scanning and digital impressions, which makes every procedure more accurate and comfortable. Had my capping done and the results are excellent."
  "The Damon braces worked faster than I expected. Dr. Ankur explained everything clearly, making it the best orthodontic experience in Amritsar.",
  "I brought my elderly father here and the staff was very patient. The dentures fit perfectly. Best dental clinic in Amritsar for seniors!",
  "My child was scared of dentists, but their pediatric section is welcoming and fun. She left smiling! Best dentist in Amritsar for kids.",
  "I had a fractured molar. The implant they placed feels and functions like a real tooth. Absolutely the best dental implant in Amritsar.",
  "Braces journey with Dr. Ankur was incredibly smooth. I now smile with full confidence. The best orthodontist in Amritsar hands down.",
  "As an NRI visiting from the US, I wanted quality care. This clinic went above and beyond with hygiene and service. Truly the best dental clinic in Amritsar.",
  "After smile designing and veneers, my friends think I’ve had work done in Dubai. Best cosmetic dentist in Amritsar by far!",
  "I got a full smile makeover done. The alignment, color, and shape of my teeth are exactly how I dreamed. The best dentist in Amritsar!",
  "My gums had chronic bleeding and recession. Their laser periodontal treatment changed everything. I highly recommend this dental clinic in Amritsar.",
  "This team took care of my 75-year-old mother like family. She’s now confident wearing her dentures again. Best dental clinic for senior citizens in Amritsar.",
  "I was able to schedule, get evaluated, and treated all in one day. Extremely professional and efficient — best dentist in Amritsar!",
  "Post-implant care was so thorough, they even called to check how I was doing. This is the kind of service that makes a clinic the best in Amritsar.",
  "I had dental trauma as a child, so I avoided dentists. But here I felt completely safe and cared for. The best dental clinic in Amritsar for anxious patients.",
  "From high-tech X-rays to detailed consultations, I felt I was in good hands. Best dental clinic in Amritsar for modern tech.",
  "The braces didn’t hurt as much as I expected, and the timeline was accurate. Dr. Ankur made the entire journey enjoyable.",
  "I got teeth polishing and cleaning done, and my breath and smile feel fresh for weeks. Best dental clinic in Amritsar for oral hygiene.",
  "Zirconia crowns were fitted so well, even I can’t tell the difference. They’ve restored both function and aesthetics. Best dentist in Amritsar!",
  "Dr. Keshvi designed my veneers to match my face shape and smile line. It’s like dental art! Best cosmetic dentist in Amritsar.",
  "Fastest and most accurate Invisalign service I’ve ever seen. Best orthodontist in Amritsar for modern braces!",
  "Tooth-colored fillings were done with such care. I can’t even see where the cavities were. This clinic offers premium work!",
  "Gum therapy here worked wonders on my bleeding gums. Completely pain-free. Best dental clinic in Amritsar for soft tissue treatment.",
  "My 6-year-old needed fillings and didn’t even flinch. Their pediatric dentist is incredible. Highly recommended for children.",
  "The digital impression technology amazed me. It was clean, fast, and highly accurate. This place is on par with US dental clinics.",
  "Staff here is fluent in English and very cooperative, which helps NRIs like us feel comfortable. Truly global service.",
  "I got full zirconia caps for both upper and lower arches. The finish is so natural. This is the best dental implant clinic in Amritsar.",
  "Implants were completed in three sittings as promised. Everything was so efficient. Great job by Dr. Keshvi and team!",
  "I was explained the treatment, pricing, pros, and cons — very transparent. I trust them completely. Best dental clinic in Amritsar for honest opinions.",
  "They even helped me understand dietary and cleaning practices post-treatment. They care beyond the procedure itself.",
  "Capping work looks so real that nobody can tell I had dental treatment. Hats off to their precision.",
  "The whole team is warm, welcoming, and professional. I never once felt like 'just another patient'. Best dentist in Amritsar!",
  "They gave my father a confident smile back with comfortable dentures. He is finally able to eat properly again.",
  "I went to them for a root canal after reading online reviews — I was not disappointed. It was the smoothest dental visit I’ve had in India.",
  "Every tool was unwrapped in front of me. Their sterilization protocol is top-notch. Best dental clinic for safety post-COVID.",
  "This clinic helped me get over my fear of dentists. Friendly team, modern tools, and no pain. Now I enjoy my visits.",
  "My case required bite correction, orthodontic alignment, and implants — all done under one roof. Seamless experience. Highly recommend.",
  "Dr. Keshvi has great chairside manner and deep expertise. I trust her with my entire family’s dental needs.",
  "You can tell the doctors are passionate about their work. They go beyond just treating and actually educate you too.",
  "Wisdom tooth surgery was quick, painless, and I had no swelling after. Easily the best dentist for oral surgery in Amritsar.",
  "My child’s first dental experience here was so positive, she’s no longer scared. Amazing pediatric care!",
  "This clinic is built around patient comfort — digital tools, clean spaces, and soft-spoken professionals. Best experience ever!",
  "Got my smile makeover in under 10 days while visiting from Canada. They really value your time.",
  "No surprise costs. Everything was quoted upfront and stuck to. Integrity like this is rare.",
  "I’ve been to clinics in Delhi and Mumbai, but none compare to the expertise and warmth here in Amritsar.",
  "They maintain photographic records at every stage of treatment — this transparency made me feel secure.",
  "They allowed me to see everything on a digital screen before, during, and after treatment. Very reassuring.",
  "For cosmetic and functional treatments, this clinic is unmatched in Punjab. They blend aesthetics with precision.",
  "I used to hide my smile. After veneers here, I smile wide in every photo. Best dentist in Amritsar for confidence boost.",
  "Came in with dental anxiety. Left with a full set of functioning and beautiful teeth. This place is life-changing.",
  "Even the receptionist followed up after my treatment to check recovery. Now that’s 5-star service.",
  "It’s hard to impress me — but this clinic did. Everything was organized, hygienic, and world-class.",
  "I got my post-implant smile makeover just in time for my sister’s wedding. Couldn’t have been more thankful!"
  "They corrected my gummy smile with precision and care. I never thought a smile could be redesigned so beautifully!",
  "I had multiple cavities filled. The color match and shape make it look like I never had a problem. Amazing work!",
  "The best part was zero pressure. They educated me, gave options, and let me decide. Pure professionalism.",
  "After 20 years of dental fear, I finally completed my treatment here — pain-free and with full trust in the team.",
  "They don’t overbook appointments. Every session is calm, focused, and respectful of your time.",
  "I’ve had three family members treated here and each time the experience was consistently excellent.",
  "My Invisalign aligners were perfectly customized, and the whole team helped me track progress digitally.",
  "As someone very particular about cleanliness, this clinic exceeded my expectations on all hygiene standards.",
  "Their cosmetic expertise goes beyond just smile design — they make sure your bite and function are perfect too.",
  "Each step of my crown placement was photographed and explained. Very few dentists do this level of documentation.",
  "I visited from the UK and was blown away by their modern approach and transparent pricing.",
  "Got zirconia crowns and bridges — they look amazing and I chew better than ever before!",
  "Even the billing process was smooth. The staff handles insurance queries and paperwork like pros.",
  "They have an in-house lab, which makes turnaround time so much faster than other clinics.",
  "No language barrier at all. As an NRI, that’s important. Everyone here speaks fluent English and Punjabi.",
  "Clinic aesthetics are relaxing — from aroma to colors, everything reduces anxiety. Very thoughtfully built.",
  "Every review I read before visiting turned out to be true. This really is the best dental clinic in Amritsar.",
  "I had to get dental work done urgently during my visit from Australia. They accommodated me without delay.",
  "After full mouth implants, I feel like I’m 20 years younger. This place gave me a new lease on life!",
  "They blend traditional care with modern science. This makes them stand out from every other clinic I’ve seen.",
  "I watched my 65-year-old uncle eat corn on the cob again after his implant treatment here. Life-changing!",
  "Transparent from day one — no hidden costs, no surprise procedures. Trustworthy dental care!",
  "From root canal to crown fitting, I had everything done here with total comfort and confidence.",
  "I love their system of treatment summaries and progress charts — very helpful for record keeping.",
  "My 10-year-old nephew had his cavity filled with cartoons playing in the background. No tears at all!",
  "They advised me against a treatment I didn’t need — that honesty is rare and appreciated.",
  "Dr. Ankur handled my complex orthodontic case with ease. I now have a perfect smile thanks to him.",
  "I never thought implants could feel this real. Eating and smiling have become effortless again.",
  "Everything is explained using diagrams and 3D scans. You’re never in the dark about what’s happening.",
  "My family dentist abroad praised the work done here — said it was top-level quality!",
  "After getting implants and crowns here, I’ve recommended them to over 10 relatives. Everyone's happy.",
  "They follow up not just by phone, but also via WhatsApp with progress updates. Very helpful!",
  "You can see the before-after photos right in the clinic. The transformations are incredible.",
  "During my daughter's braces treatment, they provided full guidance on hygiene and food. Great aftercare!",
  "This was the first time I looked forward to a dental appointment. The environment makes a big difference.",
  "They helped fix my speech issue that I thought was permanent. It was all due to my bite!",
  "My post-surgical care was done like a hospital. Dressings, checks, healing — all very organized.",
  "The clinic is well ventilated, sanitized regularly, and has purified water systems. Total safety!",
  "Dr. Keshvi combines empathy with excellence. You don’t feel rushed, and results are always on point.",
  "As a medical professional myself, I found their protocol meticulous. I now refer my own patients here.",
  "They even cleaned and repaired my old bridge while I was waiting. Proactive and generous service.",
  "My husband's implant denture clicks into place like magic. He says it feels better than his natural teeth.",
  "They explain bite force, muscle balance, and jaw posture. This isn’t just dental — it’s holistic.",
  "Even with a packed schedule, they made time for my emergency case without hesitation. Grateful!",
  "Best smile correction service I’ve ever experienced. I finally feel proud to show my teeth.",
  "Multiple procedures, one clinic — that saved time, stress, and extra travel. Extremely convenient!",
  "They don’t use temporary fixes. Every procedure is built to last and maintain oral health long-term.",
  "Even senior citizens find it easy to follow their treatment plans. My grandmother felt empowered.",
  "Full mouth rehab took a few months, but every stage was perfectly scheduled and executed.",
  "They set realistic expectations and then surpassed them. This is the sign of a truly great clinic.",
  "The smile I have today is all thanks to them. They didn’t just fix my teeth — they restored my confidence!"

// API to get a review app.get('/get-review', (req, res) => { if (reviews.length === 0) { return res.json({ review: "No reviews left!" }); } const randomIndex = Math.floor(Math.random() * reviews.length); const selectedReview = reviews[randomIndex];

// Remove the review from the array reviews.splice(randomIndex, 1);

res.json({ review: selectedReview });

});

// Serve index.html when visiting "/" app.get('/', (req, res) => { res.sendFile(path.join(__dirname, 'index.html')); });

app.listen(PORT, () => { console.log(Server running on http://localhost:${PORT}); });
